### ISSUE TITLE
Possible bug in Skill 

### ISSUE THREAD

**Issue by Em4nu3lV1ct0r** [Vicen04/Dw1DataAndPatches#10]
the Static Select skill is weird on Phoenixmon, video and save attached.I tested the vanilla version on the same save but the bug doesn't happen.

[Memory Card 1.zip](https://github.com/user-attachments/files/16831654/Memory.Card.1.zip)
[Phoenixmon Static Elect Bug.zip](https://github.com/user-attachments/files/16831655/Phoenixmon.Static.Elect.Bug.zip)

**Comment by Vicen04** [comment]
Okay, that is just a misplaced byte in the animation of "static elec", I'll have a look now.
I'm also working on a fix for a possible camera freeze that can happen in hardcore when you pick up the "Dimensional key", it only triggers if you are too close to the camera center when you pick it.

**Comment by Em4nu3lV1ct0r** [comment]
Nice Man, I'll close the issue.

**Comment by Vicen04** [comment]
Okay, I just uploaded a fixed version for Phoenixmon.
It comes with a couple of extra events that were supposed to be for the next version too...
1) Vegiemon now has dialogue after you recruit it.
2) If you arrive at the wrong time to Kokatorimon screen and you try to go to where it appears, some dialogue hinting about it will show up.

Both are events that were programmed but never implemented or had some broken triggers.
