### ISSUE TITLE
Feature Request in DWViceSimpleInstaller

### ISSUE THREAD

**Issue by Em4nu3lV1ct0r** [Vicen04/Dw1DataAndPatches#11]
hey man, the phoenixmon fix is ​​working perfectly, If possible I would really like this addition:

*Add Map Color Fix path in DWViceSimpleInstaller>Miscellaneous > Other Paths
![Map Colour Fix in Bonus Area](https://github.com/user-attachments/assets/792a307a-d09a-4a95-b383-84260996a9b6)

I always use it, but I have to use the ppf-o-matic3 to apply, it would be nice to have this option available in DWViceSimpleInstaller.

thanks man.

**Comment by Vicen04** [comment]
I actually forgot to add the button, there is code for it to work and the patch has been there since the start, you can actually check the "Vice hack" folder inside the patches and see it.

I just uploaded a version with the button.

**Comment by Em4nu3lV1ct0r** [comment]
thanks man, i'll close it.
