### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Em4nu3lV1ct0r** [Vicen04/Dw1DataAndPatches#20]
if you start a battle with Sharmamon and H-Kabuterimon join in:

https://github.com/user-attachments/assets/8588428c-ec9d-431d-83fd-749358ab91b2

**Comment by Vicen04** [comment]
That's another animation problem, I'll check all the ultimate animations today...

**Comment by Em4nu3lV1ct0r** [comment]
> That's another animation problem, I'll check all the ultimate animations today...

Wouldn't it be possible to remove the Sharmamons and Psychemons from this map? It would avoid the indirect confrontation with Phoenixmon and H-Kabuterimon.

**Comment by Vicen04** [comment]
But that's not the cause of the glitch... I don't see why I should remove them... You can also fight Piximon in the same way...

Anyway, after checking all of the ultimate animations again, I noticed that MetalMamemon also had 1 broken animation.

**Comment by Em4nu3lV1ct0r** [comment]
> But that's not the cause of the glitch... I don't see why I should remove them... You can also fight Piximon in the same way...
> 
> Anyway, after checking all of the ultimate animations again, I noticed that MetalMamemon also had 1 broken animation.


Actually, I didn't remember Piximon, since the concert is planned I'm going to close the Issue.
