### ISSUE TITLE
Curling mini game wont start

### ISSUE THREAD

**Issue by Snow22** [Vicen04/Dw1DataAndPatches#24]
Teleports me into cave on the spot were we play the mini game. But I can move immediately and the mini game doesn't start or even appear on the screen in anyway. Nothing interact able. Leaving just resets as if id lost. Tried every single variation I could think of in settings (duckstation). From safe mode to trying each one at a time to see if anything helps. Just appears to have bugged. Both the save game and save state I have from before encounter the same bug. Unsure if theres a fix. Would start over but want to know what I did to trigger it. Did tick the curling box before hand in patcher. Made another version without that box ticked same result.

**Comment by Vicen04** [comment]
Okay, the jump to curling it is a bit off... I was making an update to the installer anyway, I'll upload everything together.

**Comment by Snow22** [comment]
Oh also had the unlock all areas ticked. Not sure if that could of been the culprit either

**Comment by Vicen04** [comment]
No, it is an issue in the main 2.0.2 patch, I'll upload a fix later, I'm still working on the update for the installer

**Comment by Snow22** [comment]
Awesome cheers!

**Comment by Vicen04** [comment]
It has been updated.

**Comment by Vicen04** [comment]
It should be solved, so I'm closing this
