### ISSUE TITLE
Broken text in one Mojyamon vending igloo

### ISSUE THREAD

**Issue by LinconEduardo** [Vicen04/Dw1DataAndPatches#4]
Hi, i admirate very much the job u and Maeson made for DGW1
i dont see anywhere to post or report directly Maeson 

but in recenty Patch Version 1.08e one Mojyamon have the text broken in screen (this dont afect gameplay is just a visual glitch), i think is cause is the renaming of some itens.

keep the good job, ty u so much <3

**Comment by Vicen04** [comment]
Hi,

I have sent Maeson the way to fix that issue, so an update should be uploaded soon (I don't know when). 

It is a visual issue that already happens in the vanilla game, but one of the patches make it stand out a lot more. It is related to the Giromon's Jukebox fix.

**Comment by LinconEduardo** [comment]
i maybe be wrong, but i dint notice the bug in vanilla game

anyway thanks for answer <3
