### ISSUE TITLE
Feeding baby and in-training digimon with evolutionary itens

### ISSUE THREAD

**Issue by LinconEduardo** [Vicen04/Dw1DataAndPatches#5]
Ive found some day is the baby and in-training digimon wont refuse eating a evolutionary item. And nothing ill happens when they eat that.

Champion refuses another champion and ultimate digimon ill refuse eat both champion and ultimate itens.

**Comment by Vicen04** [comment]
Is this for the vanilla game?

I'm pretty sure this cannot happen in neither my hack or Maeson's hack.

About items being refused by champion/ultimates:

- Champions cannot evolve to other champions using items, that is intended and part of the original game.
- Ultimates cannot evolve at all, except for some exceptions; that is also intended and from the original game.
