### ISSUE TITLE
Same Glitch in 4 places?

### ISSUE THREAD

**Issue by Reza702-ux** [Vicen04/Dw1DataAndPatches#6]
So, I started a new save game with the ViceHack patch and a few useful patches and ran into a glitch that seemingly occurs in 4 places; 

1. Punimon resting chair,
2.  battle save machine,
3.  Monochrome shop and 
4. Whamon in the city. 

Basically, whenever I talk to Punimon about resting and say yes, the game freezes. Same thing occurs in the shop after the invisible bridge (after I try to haggle with a customer), when I choose to save with the battle save machine and choose yes, and also when I choose Factorial Town with Whamon in the city. I thought I used too many patches, so I simply used the vice hack and its hardmode patch, played through again, but had the same issues. If I use a clean iso without the hack, I don't have those issues. 

I'm using the latest patch on the Duckstation emulator. Used both official saves and savestates.

**Comment by Vicen04** [comment]
Hi,

Would you let me know which version of the patch this is for (or the date it was created if it does not have a version name), I know that the patches have sometimes issues with Duckstation.

It is weird for this to happen with either Punimon, the save machine or Whamon, since I have not modified neither of them at all.

**Comment by Reza702-ux** [comment]
It was the US version, and it was a BIN file, and it seems that the third problem was my issue. I simply made a folder and copied the patches I wanted to apply, but I applied the Vice Hack AFTER the better tech chance patch because that's how it was arranged in the folder. Sorry about that. And great patch!
